---
title: "Exercise 9"
author: "Tobias Raidl, 11717659"
date: "2023-01-01"
output:
  pdf_document:
    toc: true
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy=TRUE)
```

## Setup
```{r}
library(dplyr)
library(MASS)
wine <- read.csv("winequality-white.csv",dec=".",sep=";")

y = factor(c(), levels=c("Low", "High"))

wine$class[wine$quality %in% c(3,4,5)] = "Low"
wine$class[wine$quality %in% c(6,7,8,9)] = "High"
df = dplyr::select(wine, -quality)
sample <- sample(c(TRUE, FALSE), nrow(df), replace=TRUE, prob=c(2/3,1/3))
train  <- df[sample, ]
test   <- df[!sample, ]
```

### 1.
```{r}
library(ggplot2)
ggplot(data=df, aes(x=alcohol, y=fixed.acidity, col=class)) +
  geom_point()
```

#### a)
```{r}
lda = lda(class~alcohol+fixed.acidity, data=train)
test$pred = predict(lda, newdata=test)$class

get_missclass_rate = function(gt, pred) {
  conf_mat = table(gt, pred, deparse.level=2, dnn=c("gt", "pred"))
  tp = conf_mat[1,1]
  tn = conf_mat[2,2]
  fp = conf_mat[1,2]
  fn = conf_mat[2,1]
  misclass_rate = (fp + fn) / sum(conf_mat)
  return(misclass_rate)
}

print(paste("misclassification_rate", get_missclass_rate(test$class, test$pred)))

ggplot(data=test, aes(x=alcohol, y=fixed.acidity, col=pred)) +
  geom_point()
```

#### b)
```{r}
grid = data.frame(alcohol=seq(from=8, to=14, length.out=100), 
           fixed.acidity=seq(from=3, to=15, length.out=100))
grid = expand.grid(grid$alcohol, grid$fixed.acidity)
colnames(grid) = c("alcohol", "fixed.acidity")
grid$pred = predict(lda, newdata=grid)$class

ggplot(data=grid, aes(x=alcohol, y=fixed.acidity, col=pred)) +
  geom_point()
```

#### c)
```{r}
qda = qda(class~alcohol+fixed.acidity, data=train)
test$qda_pred = predict(qda, newdata=test)$class

print(paste("misclassification_rate", get_missclass_rate(test$class, test$qda_pred)))

ggplot(data=test, aes(x=alcohol, y=fixed.acidity, col=qda_pred)) +
  geom_point()

grid$qda_pred = predict(qda, newdata=grid)$class

ggplot(data=grid, aes(x=alcohol, y=fixed.acidity, col=qda_pred)) +
  geom_point()
```

#### d)
```{r}
library(rrcov)
rob_lda = Linda(class~alcohol+fixed.acidity, data=train)
test$rob_lda_pred = predict(rob_lda, dplyr::select(test, c(alcohol, fixed.acidity)))@classification

print(paste("misclassification_rate", get_missclass_rate(test$class, test$rob_lda_pred)))

ggplot(data=test, aes(x=alcohol, y=fixed.acidity, col=rob_lda_pred)) +
  geom_point()

grid$rob_lda_pred = predict(rob_lda, dplyr::select(grid, c(alcohol, fixed.acidity)))@classification

ggplot(data=grid, aes(x=alcohol, y=fixed.acidity, col=rob_lda_pred)) +
  geom_point()
```

```{r}
library(rrcov)
rob_qda = QdaCov(class~alcohol+fixed.acidity, data=train)
test$rob_qda_pred = predict(rob_qda, dplyr::select(test, c(alcohol, fixed.acidity)))@classification

print(paste("misclassification_rate", get_missclass_rate(test$class, test$rob_qda_pred)))

ggplot(data=test, aes(x=alcohol, y=fixed.acidity, col=rob_qda_pred)) +
  geom_point()

grid$rob_qda_pred = predict(rob_qda, dplyr::select(grid, c(alcohol, fixed.acidity)))@classification

ggplot(data=grid, aes(x=alcohol, y=fixed.acidity, col=rob_qda_pred)) +
  geom_point()
```

#### e) #TODO

### 2.
```{r}
iters = 5
lda_misclass_rates = vector("numeric", iters)
qda_misclass_rates = vector("numeric", iters)
rob_lda_misclass_rates = vector("numeric", iters)
rob_qda_misclass_rates = vector("numeric", iters)

for (i in 1:iters) {
  df = dplyr::select(wine, -quality)
  set.seed(i)
  sample <- sample(c(TRUE, FALSE), nrow(df), replace=TRUE, prob=c(2/3,1/3))
  train  <- df[sample, ]
  test   <- df[!sample, ]

  lda = lda(class~., data=train)
  lda_pred = predict(lda, newdata=test)$class
  lda_misclass_rates[i] = get_missclass_rate(test$class, lda_pred)
  
  qda = qda(class~., data=train)
  qda_pred = predict(qda, newdata=test)$class
  qda_misclass_rates[i] = get_missclass_rate(test$class, qda_pred)
  
  rob_lda = Linda(class~., data=train)
  rob_lda_pred = predict(rob_lda, dplyr::select(test, -class))@classification
  rob_lda_misclass_rates[i] = get_missclass_rate(test$class, rob_lda_pred)
  
  rob_qda = QdaCov(class~., data=train)
  rob_qda_pred = predict(rob_qda, dplyr::select(test, -class))@classification
  rob_qda_misclass_rates[i] = get_missclass_rate(test$class, rob_qda_pred)
}

library(reshape2)

df_misclass_rates = data.frame(id=1:iters, lda=lda_misclass_rates, qda=qda_misclass_rates, rob_lda=rob_lda_misclass_rates, rob_qda=rob_qda_misclass_rates)

data_mod = melt(df_misclass_rates, id.vars="id", measure.vars=c("lda", "qda", "rob_lda", "rob_qda"))

ggplot(data_mod) + 
  geom_boxplot(aes(x=id, y=value, color=variable))
```

